"use client";
import React, { useEffect, useState } from "react";
import RightSideAuth from "../_loginComponents/RightSideAuth";
import InputLoginError from "../_loginComponents/loginInputFields/InputLoginError";
import ReactJsOtpInputModal from "@/components/inputs/ReactJsOtpInputModal";
import { SubmitHandler, useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { LoginButton } from "@/components/Buttons/LoginButton";
import BackToLogin from "../_loginComponents/BackToLogin";
import { resendOtpApi, verifyOtpApi } from "@/apis/loginApis";
import { useAppSelector } from "@/store/hook";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import cookies from "js-cookie";
import { v4 as uuidv4 } from "uuid";

const otpSchema = yup.object({
  otp: yup
    .string()
    .required("Please enter login pin")
    .min(6, "Min 6 digits required")
    .max(6, "Max 6 digits required"),
});

type Inputs = yup.InferType<typeof otpSchema>;

const OtpPage = () => {
  const router = useRouter();
  const [resendDisabled, setResendDisabled] = useState<boolean>(true);
  const [countdown, setCountdown] = useState<number>(60);

  const { loginData, email } = useAppSelector((state) => state.auth);

  const {
    setValue,
    handleSubmit,
    formState: { errors, isSubmitting },
    watch,
    reset,
  } = useForm({
    resolver: yupResolver(otpSchema),
    mode: "onChange",
    defaultValues: {
      otp: "",
    },
  });
  const otp = watch("otp");

  const deviceId = uuidv4();

  const handleOtpPage: SubmitHandler<Inputs> = async (data) => {
    const payload = {
      login: email,
      otp: data?.otp,
      reference_id: loginData?.referenceId || "",
      journey_id: loginData?.journeyId || "",
      deviceId,
    };

    const res = await verifyOtpApi(payload);
    if (res?.success) {
      toast.success(res?.data?.message ?? "Otp verified successfully!");
      reset();
      cookies.set("deviceId", deviceId);
      cookies.remove("isOtp");
      cookies.set("token", res?.data?.access);
      router.push("/");
    }
  };

  const handleResendOtp = async () => {
    const res = await resendOtpApi({
      referenceId: loginData?.referenceId || "",
      journeyId: loginData?.journeyId || "",
    });
    if (res?.st) {
      setCountdown(60);
      setResendDisabled(true);
      toast.success(res?.data?.message ?? "Resend otp successfully!");
      reset();
    }
    // try {
    //   const res = await forgetPasswordApi({ email: email as string });
    //   if (res?.st) {
    //     toast.success(res?.data?.message ?? "login successfully!");
    //     reset();
    //   } else {
    //     toast.error(res?.msg ?? "Something went wrong!");
    //   }
    // } catch (error: unknown) {
    //   const err = error as AxiosError<{ message?: string; detail?: string }>;
    //   toast.error(err?.response?.data?.message ?? "Something went wrong!");
    // }
  };

  const isGoogleAuth = loginData?.isAuthSetup;

  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (resendDisabled && countdown > 0) {
      timer = setInterval(() => {
        setCountdown((prev) => prev - 1);
      }, 1000);
    } else if (countdown === 0) {
      setResendDisabled(false); // Enable the resend button after 60 seconds
    }
    return () => clearInterval(timer); // Cleanup timer on unmount
  }, [resendDisabled, countdown]);

  useEffect(() => {
    if (loginData?.otp) {
      setValue("otp", loginData?.otp);
    }
  }, [loginData?.otp]);

  return (
    <>
      <RightSideAuth
        header={isGoogleAuth ? "Verify authenticator code" : "Verify your OTP"}
        title={
          isGoogleAuth
            ? "Enter the 6-digit code generated by your Google Authenticator app to complete verification."
            : "Enter the OTP sent to your registered mobile number or email address to continue."
        }
      >
        <form
          onSubmit={handleSubmit(handleOtpPage)}
          className="mb-5 max-w-100 w-full  gap-2 flex flex-col items-center"
        >
          <div className="max-w-full  mb-2 px-0.5">
            <ReactJsOtpInputModal
              otp={otp}
              handleChange={(otp) => {
                setValue("otp", otp);
              }}
              maxlength={6}
              type="password"
              autoFocus={true}
              disabled={loginData?.otp ? true : false}
            />

            <InputLoginError errors={errors} inputName="otp" />
          </div>

          <div>
            {isGoogleAuth ? (
              <>
                <p className="text-darkOlive text-font14 text-center font-light">
                  Don&apos;t have an authenticator code?{" "}
                  <button
                    type="button"
                    className={`text-avocado font-semibold text-font14 ${" cursor-pointer"}`}
                    onClick={() => {}}
                  >
                    disable 2FA
                  </button>
                </p>
              </>
            ) : (
              <p className="text-darkOlive text-font14 text-center font-light">
                If you don&apos;t receive the code!{" "}
                <button
                  type="button"
                  disabled={resendDisabled}
                  className={`text-avocado font-semibold text-font14 ${
                    resendDisabled
                      ? "opacity-50 cursor-not-allowed"
                      : " cursor-pointer"
                  }`}
                  onClick={() => {
                    setValue("otp", "");
                    handleResendOtp();
                  }}
                >
                  {countdown > 0 ? `in (${countdown} seconds)` : ""} Resend
                </button>
              </p>
            )}
          </div>
          <LoginButton isSubmitting={isSubmitting} />

          <BackToLogin isSubmitting={isSubmitting} />
        </form>
      </RightSideAuth>
    </>
  );
};

export default OtpPage;
